### ISSUE TITLE
get-incident: TypeError: Object of type 'ReadResponse' is not JSON serializable

### ISSUE THREAD

**Issue by kellerkind** [greenpau/pycherwell#11]
# Steps to reproduce

1. Select a valid cherwell incident id
2. Perform cli 

```
cherwell-client --get-incident 71394
```

# Current behavior

```
[
    Traceback (most recent call last):
  File "/home/user/.virtualenvs/cherwell/bin/cherwell-client", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/user/pycherwell/cherwell-client", line 122, in <module>
    main()
  File "/home/user/pycherwell/cherwell-client", line 117, in main
    json.dump(data, args.output, sort_keys=True, indent=4, separators=(',', ': '))
  File "/usr/lib64/python3.6/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/lib64/python3.6/json/encoder.py", line 428, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/lib64/python3.6/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/lib64/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/usr/lib64/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ReadResponse' is not JSON serializable
```

# Wanted behavior

Output the details of the incident number.

**Comment by greenpau** [comment]
@kellerkind , did you install from source or did you use pip?

**Comment by kellerkind** [comment]
Its installed from source.

**Comment by greenpau** [comment]
@kellerkind , I need to update the source code with the ability to fetch incident by id. Will try doing it later today.

**Comment by kellerkind** [comment]
when using format `yaml` I get another output: 

```
cherwell-client --get-incident 71394 --format yaml
```

results in:

```
  File "/home/user/.virtualenvs/cherwell/lib/python3.6/site-packages/yaml/representer.py", line 52, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "/home/user/.virtualenvs/cherwell/lib/python3.6/site-packages/yaml/representer.py", line 317, in represent_object
    reduce = data.__reduce_ex__(2)
TypeError: can't pickle _thread.RLock objects
```

**Comment by kellerkind** [comment]
@greenpau Could be the root cause, that openapi generated models are not serializable by default?

Update: Answered for myself. The model has its [to_dict](https://github.com/greenpau/pycherwell/blob/87d45599e56aa3f6208a712d449619f859c04c4d/pycherwell/models/read_response.py#L259) method which can be used for serialization. One question that is left for me why the ReadResponse is wrapped by a tuple?

**Comment by greenpau** [comment]
> @greenpau Could be the root cause, that openapi generated models are not serializable by default?

@kellerkind , the client code is a wrapper around the library itself. The code that exists [here](https://github.com/greenpau/pycherwell/blob/master/pycherwell/app_client.py#L170-L193) is not up-to-date.

**Comment by greenpau** [comment]
@kellerkind , PR is more than welcomed 😄

**Comment by gthieleb** [comment]
FYI, I'll continue with my other GH profile...

**Comment by greenpau** [comment]
This is complete.
