### ISSUE TITLE
get-incident first run fails

### ISSUE THREAD

**Issue by gthieleb** [greenpau/pycherwell#15]
Perhaps this is wanted behavior. But with unpopulated business_objects this appears.

Steps to reproduce:

1. Remove `~/.cherwell/business_objects.json`

2. `cherwell-client --get-incident 4711`

Current behavior:

```
Traceback (most recent call last):
  File "/home/user/.virtualenvs/cherwell/bin/cherwell-client", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/user/pycherwell/cherwell-client", line 131, in <module>
    main()
  File "/home/user/pycherwell/cherwell-client", line 108, in main
    data = cli.get_incident(opts)
  File "/home/user/pycherwell/pycherwell/app_client.py", line 193, in get_incident
    item_oid = self.config.get_business_object('Incident')
  File "/home/user/pycherwell/pycherwell/app_configuration.py", line 280, in get_business_object
    if name in self.app['business_objects_ref']:
KeyError: 'business_objects_ref'
```

Desired behavior:

Output:
```
{
    "bus_ob_id": "6dd53665c0c24cab86870a21cf6434ae",
    "bus_ob_public_id": "4711",
    "bus_ob_rec_id": "943751f0ee4c9bc93652b749f0ba4d01df64903aa8",
    "error_code": null,
    "error_message": null,
    "fields": [
...
```

**Comment by greenpau** [comment]
> Perhaps this is wanted behavior. But with unpopulated business_objects this appears.

@gthieleb , I need to add the logic to detect absent/missing business objects.
